# Generated by Django 4.0.4 on 2023-07-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_stat_inst', '0012_delete_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_void', models.BooleanField(default=False)),
                ('ref_completed', models.BooleanField(default=False)),
                ('ref_no', models.CharField(blank=True, max_length=100)),
                ('refferal_to', models.CharField(blank=True, max_length=100)),
                ('reason_for_referral', models.CharField(blank=True, max_length=100)),
                ('reason_for_referral_others', models.CharField(blank=True, max_length=100)),
                ('documents_attached', models.CharField(blank=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'si_case_referrals',
            },
        ),
    ]
